// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1aBB_gCcUTPTQsKf2d8C4S10L_vxbBRg',
    appId: '1:392734125595:web:a1a510ff915de7eeecd2be',
    messagingSenderId: '392734125595',
    projectId: 'elbi-donation-b668a',
    authDomain: 'elbi-donation-b668a.firebaseapp.com',
    storageBucket: 'elbi-donation-b668a.appspot.com',
    measurementId: 'G-WQKJN0LB5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1qrO-NTOvzWRq9dUHWkz72fZ3ItaP5eQ',
    appId: '1:392734125595:android:8fb4b3c66daccca3ecd2be',
    messagingSenderId: '392734125595',
    projectId: 'elbi-donation-b668a',
    storageBucket: 'elbi-donation-b668a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxBddfdnfKImNJFCTAO7mg1KDxe_VSgPQ',
    appId: '1:392734125595:ios:0630a0fc2eb409a3ecd2be',
    messagingSenderId: '392734125595',
    projectId: 'elbi-donation-b668a',
    storageBucket: 'elbi-donation-b668a.appspot.com',
    iosBundleId: 'com.example.cmsc23Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxBddfdnfKImNJFCTAO7mg1KDxe_VSgPQ',
    appId: '1:392734125595:ios:0630a0fc2eb409a3ecd2be',
    messagingSenderId: '392734125595',
    projectId: 'elbi-donation-b668a',
    storageBucket: 'elbi-donation-b668a.appspot.com',
    iosBundleId: 'com.example.cmsc23Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1aBB_gCcUTPTQsKf2d8C4S10L_vxbBRg',
    appId: '1:392734125595:web:5487f37cf70753acecd2be',
    messagingSenderId: '392734125595',
    projectId: 'elbi-donation-b668a',
    authDomain: 'elbi-donation-b668a.firebaseapp.com',
    storageBucket: 'elbi-donation-b668a.appspot.com',
    measurementId: 'G-50GND9F77W',
  );
}
